version: "3.3"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  bytebase:
    image: bytebase/bytebase:2.22.3
    ports:
      - "8080:8080"
    volumes:
      - ~/.bytebase/data:/var/opt/bytebase
    
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#      - "9090:9090"
#    environment:
#      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
#      - REDIS_ADDRESS=redis:6379
#    depends_on:
#      - postgres
#      - redis
#    entrypoint:
#      [
#        "/app/wait-for.sh",
#        "postgres:5432",
#        "--",
#        "/app/start.sh"
#      ]
#    command: [ "/app/main" ]
volumes:
  data-volume:
